/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef obs_thrift_server_CONSTANTS_H
#define obs_thrift_server_CONSTANTS_H

#include "obs_thrift_server_types.h"



class obs_thrift_serverConstants {
 public:
  obs_thrift_serverConstants();

};

extern const obs_thrift_serverConstants g_obs_thrift_server_constants;



#endif
