/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "obs_thrift_server_constants.h"



const obs_thrift_serverConstants g_obs_thrift_server_constants;

obs_thrift_serverConstants::obs_thrift_serverConstants() {
}



