#
# Autogenerated by Thrift Compiler (0.14.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TFrozenDict, TException, TApplicationException
from thrift.protocol.TProtocol import TProtocolException
from thrift.TRecursive import fix_spec

import sys

from thrift.transport import TTransport
all_structs = []


class SourceDimensions(object):
    """
    Attributes:
     - leftMargin
     - topMargin
     - relativeWidth
     - relativeHeight

    """


    def __init__(self, leftMargin=0, topMargin=0, relativeWidth=1.0000000000000000, relativeHeight=1.0000000000000000,):
        self.leftMargin = leftMargin
        self.topMargin = topMargin
        self.relativeWidth = relativeWidth
        self.relativeHeight = relativeHeight

    def read(self, iprot):
        if iprot._fast_decode is not None and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None:
            iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
            return
        iprot.readStructBegin()
        while True:
            (fname, ftype, fid) = iprot.readFieldBegin()
            if ftype == TType.STOP:
                break
            if fid == 1:
                if ftype == TType.I32:
                    self.leftMargin = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 2:
                if ftype == TType.I32:
                    self.topMargin = iprot.readI32()
                else:
                    iprot.skip(ftype)
            elif fid == 3:
                if ftype == TType.DOUBLE:
                    self.relativeWidth = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            elif fid == 4:
                if ftype == TType.DOUBLE:
                    self.relativeHeight = iprot.readDouble()
                else:
                    iprot.skip(ftype)
            else:
                iprot.skip(ftype)
            iprot.readFieldEnd()
        iprot.readStructEnd()

    def write(self, oprot):
        if oprot._fast_encode is not None and self.thrift_spec is not None:
            oprot.trans.write(oprot._fast_encode(self, [self.__class__, self.thrift_spec]))
            return
        oprot.writeStructBegin('SourceDimensions')
        if self.leftMargin is not None:
            oprot.writeFieldBegin('leftMargin', TType.I32, 1)
            oprot.writeI32(self.leftMargin)
            oprot.writeFieldEnd()
        if self.topMargin is not None:
            oprot.writeFieldBegin('topMargin', TType.I32, 2)
            oprot.writeI32(self.topMargin)
            oprot.writeFieldEnd()
        if self.relativeWidth is not None:
            oprot.writeFieldBegin('relativeWidth', TType.DOUBLE, 3)
            oprot.writeDouble(self.relativeWidth)
            oprot.writeFieldEnd()
        if self.relativeHeight is not None:
            oprot.writeFieldBegin('relativeHeight', TType.DOUBLE, 4)
            oprot.writeDouble(self.relativeHeight)
            oprot.writeFieldEnd()
        oprot.writeFieldStop()
        oprot.writeStructEnd()

    def validate(self):
        return

    def __repr__(self):
        L = ['%s=%r' % (key, value)
             for key, value in self.__dict__.items()]
        return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

    def __ne__(self, other):
        return not (self == other)
all_structs.append(SourceDimensions)
SourceDimensions.thrift_spec = (
    None,  # 0
    (1, TType.I32, 'leftMargin', None, 0, ),  # 1
    (2, TType.I32, 'topMargin', None, 0, ),  # 2
    (3, TType.DOUBLE, 'relativeWidth', None, 1.0000000000000000, ),  # 3
    (4, TType.DOUBLE, 'relativeHeight', None, 1.0000000000000000, ),  # 4
)
fix_spec(all_structs)
del all_structs
